audit_header: false
title: Frisco Real Estate Video Blog with Amy and Kevin Smits
description: Our mission at The Smits Team is to be your best resource for Frisco real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Smits Team, your professional Frisco Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: true
custom_links_new_tab:
  - title: Our Listings
    url: https://www.thesmitsteam.com/results-gallery/
  - title: Meet The Team
    url: https://www.thesmitsteam.com/agents/

client:
  name: Amy and Kevin Smits
  title:
  license_number:
  about_markdown: |
    Amy and Kevin Smits decided early on in their careers that the real estate process was too involved for one or two people to handle effectively. The Smits Team was a direct result of their pursuit of hiring specialists for each and every step of the real estate transaction. If you would like to learn more about how The Smits Team works with buyers, watch this video

    Teamwork is vital in your purchase. Imagine if you use an agent working alone and they are on vacation, sick or otherwise unable to show you property or worse yet, miss an important deadline! Are you willing to risk losing the property of your dreams because your agent isn't available? I wouldn't either. To find out how The Smits Team works together, watch our team video here
  brand: The Smits Team
  brokerage:
  market: Frisco
  address: 507 Main Street, Box 571<br>Frisco, CO 80443
  phone: 970-333-3029
  phone_type:
  phone2:
  phone2_type:
  email: Info@TheSmitsTeam.com
  url: https://www.TheSmitsTeam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.vailsummithomesearch.com/homevalue/value
  second_CTA_text: Home Search
  second_CTA_URL: http://www.vailsummithomesearch.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Whatâ€™s Your Frisco Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.vailsummithomesearch.com/homevalue/value

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Frisco Home?"
    CTA_text2: "Search the entire MLS for your Frisco home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.vailsummithomesearch.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Century21Gold
  linkedin_url: https://www.linkedin.com/company/the-smits-team
  youtube_url: https://www.youtube.com/user/SmitsTeamTV
  twitter_url: http://thesmitsteam.blogspot.com/#
  instagram_url:
  pinterest_url:
  # zillow_url: http://www.zillow.com/profile/Amy-Smits/Reviews/?scrnnm=Amy%20Smits
  # trulia_url: http://www.trulia.com/profile/amy-smits-broker-80435-302033/overview
  google_reviews_url: https://search.google.com/local/writereview?placeid=ChIJO1A2gZBeaocROnd8giRNjv4
  yelp_url:
  podcast_url:

podcast:
  title: 'Frisco Real Estate Podcast with Amy and Kevin Smits'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Frisco Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Smits Team - your professional Frisco Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Frisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Amy and Kevin Smits'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Colorado Resorts Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#be6f93'
  accent_color: '#FF48B0'
  theme_color: '#333a40'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
